name: Gapi
main: com.crazicrafter1.gapi.Main
version: 1.0.5 # last: 1.0.4
api-version: 1.13
softdepend: [CRUtils]
author: crazicrafter1
commands:
  testmenu:
    description: Test that the menus work properly
    permission: gapi.admin
permissions:
  gapi.admin:
    description: Enable Gapi admin
    default: op

# 1.0.5 (2/17/2022)
# release for lootcrates


# 1.0.4 (2/5/2022)
# 1.12.2 support


# 1.0.3 (1/14/2022)
# 1.18.1 support + fixes


# 1.0.2 (10/17/2021)
# prettier menu titles


# 1.0.1 (10/15/2021)
# hotfixes


# 1.0.0 (10/12/2021)
# first version