name: Gapi
main: com.crazicrafter1.gapi.Main
version: 1.0.0 # first version!
api-version: 1.13
softdepend: [CRUtils]
author: crazicrafter1
commands:
  testmenu:
    description: Test that the menus work properly
    usage: /<command> <simple | locked>
    permission: gapi.admin
permissions:
  gapi.admin:
    description: Enable Gapi admin
    default: op

# 1.0.0 (10/12/2021)
# first version