name: Gapi
main: com.crazicrafter1.gapi.Main
version: 1.0.0
author: crazicrafter1
api-version: 1.17
depend: [CRUtils]
commands:
  testmenu:
    description: Test that the menus work properly
    usage: /<command> [simplex | parallax]
    permission: gapi.admin
permissions:
  gapi.admin:
    description: Enable Gapi admin
    default: op